[package]
name = "dragncards-marvelcdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.163", features = ["derive"] }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.3.3", features = ["serde", "v5"] }

[dev-dependencies]
serde_json = "1.0.96"
tokio-test = "0.4.2"
